services:
    ansible-ui:
        ports:
            - 3060:3000
        image: semaphoreui/semaphore:v2.16.47
        environment:
            SEMAPHORE_DB_DIALECT: sqlite
            SEMAPHORE_ADMIN: admin
            SEMAPHORE_ADMIN_PASSWORD: asdasd
            SEMAPHORE_ADMIN_NAME: yash
            SEMAPHORE_ADMIN_EMAIL: admin@localhost.com
            SEMAPHORE_USE_REMOTE_RUNNER: "True"
            SEMAPHORE_RUNNER_REGISTRATION_TOKEN: "xxx"
        volumes:
            - semaphore_data:/var/lib/semaphore
            - semaphore_config:/etc/semaphore
            - semaphore_tmp:/tmp/semaphore
volumes:
    semaphore_data:
    semaphore_config:
    semaphore_tmp:
